import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import './globals.css';
import ConvexClientProvider from './ConvexClientProvider';

import { fonts } from '@/lib/fonts';
import { cn } from '@/lib/utils';

import { Toaster } from '@/components/ui/toaster';
import { Header } from '../components/navbar/header';
import { Footer } from '../components/footer/footer';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn('min-h-screen font-sans', fonts)}>
                {/* <body className={inter.className}> */}
                <ConvexClientProvider>
                    <Toaster />
                    <Header />
                    {children}
                    <Footer />
                </ConvexClientProvider>
            </body>
        </html>
    );
}
